backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: static/img
public_folder: content/images

collections:
  - name: "pages"
    label: "Pages"
    files:
      - { label: "Title", name: "title", widget: "string" }
      - label: "Landing Page"
        name: "landing"
        file: "content/landing-page.md"
        widget: "list"
        types: 
          - label: "About"
            name: "about"
            widget: object
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Featured Image", name: "image", widget: "image" }
              - { label: "Description", name: "description", widget: "markdown", default: "content/images/roto.jpg"}
          - {label: "Dummy Text", name: "dummy", widget: "markdown" }
          



    